### ISSUE TITLE
[Dev] Overlay loading component

### ISSUE THREAD

**Issue by hgcassiopeia** [BKK-WeSpace/tree-population#10]
Loading component looks like [Tree Bangkok](https://tree.bangkok.go.th/)

Note: 
- [MUI Backdrop](https://mui.com/material-ui/react-backdrop/)
- [MUI Progress](https://mui.com/material-ui/react-progress/)

Example:
![Screen Shot 2566-03-16 at 20 24 21](https://user-images.githubusercontent.com/20450777/225631179-55db28ca-5150-469e-976d-7e48bba536b6.png)

**Comment by pavitpim40** [comment]
@flooksan already finish this issue
