### ISSUE TITLE
[Dev] Navbar Component

### ISSUE THREAD

**Issue by hgcassiopeia** [BKK-WeSpace/tree-population#18]
- Create Navbar Component

![Screen Shot 2566-03-18 at 20 28 31](https://user-images.githubusercontent.com/20450777/226109235-11b8d6f5-3ce9-46bc-b401-7a3960cf1895.png)

**Comment by nen108** [comment]
import React from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import { Navbar, Nav } from "react-bootstrap";

const WeSpaceNavbar = () => {
  return (
    <Navbar bg="light" expand="lg">
      <Navbar.Brand href="#home" style={{paddingLeft:30}}><b>We</b><span style={{color:'#94B045'}}><b>Space</b></span></Navbar.Brand>
      <Navbar.Toggle aria-controls="basic-navbar-nav" />
      <Navbar.Collapse id="basic-navbar-nav">
        <Nav
          className="ml-auto d-flex justify-content-end"
          style={{ width: "100%",paddingRight:30 }}
        >
          <Nav.Link href="#about"><img src='https://cdn3.iconfinder.com/data/icons/spring-23/32/branch-leaf-spring-easter-nature-ecology-green-256.png' width='20' height='20'/><b> เกี่ยวกับเรา</b></Nav.Link>
          <Nav.Link href="#contribute"><img src='https://cdn3.iconfinder.com/data/icons/activity-6/512/activity_sport-77-256.png' width='20' height='20'/><b> Contribute us</b></Nav.Link>
        </Nav>
      </Navbar.Collapse>
    </Navbar>
  );
};

export default WeSpaceNavbar;

**Comment by shyamtawli** [comment]
@nen108 you can open a PR regarding it. why you add the code here.
