### ISSUE TITLE
[Dev] Contribute us Component

### ISSUE THREAD

**Issue by hgcassiopeia** [BKK-WeSpace/tree-population#20]
Create contribute us component

![Screen Shot 2566-03-18 at 20 32 19](https://user-images.githubusercontent.com/20450777/226110543-4b378779-bdb2-4de5-b9f4-885f59b6a513.png)

**Comment by S1ddG** [comment]
Hi @hgcassiopeia can you assign it to me?

**Comment by pavitpim40** [comment]
@S1ddG I'll assign this taskto you. Are you familiar with react and MUI  rigth ?

**Comment by S1ddG** [comment]
Yes! you can provide me the requirements of this component and i will start working on it

**Comment by S1ddG** [comment]
Hi @hgcassiopeia where do you want this modal popup to happen? And what triggers this modal popup?

**Comment by pavitpim40** [comment]
@S1ddG Yes, you can create a dedicated button for triggers modal from landing page. In coding style you can follow from existing code or you can improve it, we not strictly now.  

Thank you for your contribute :)

**Comment by S1ddG** [comment]
@pavitpim40 Thanks for the quick response..Also, you have used icons in the modal heading. I have never used those...How do you guys import them? is there any ID or Codes for those icons?
example: 🌿

**Comment by pavitpim40** [comment]
@S1ddG I think you can use this icon for this task. 

<img width="609" alt="Screenshot 2566-03-21 at 12 13 03" src="https://user-images.githubusercontent.com/63455126/226524016-eb200801-8108-418c-844f-61f3f009f520.png">
